service:
  name: we-backend

plugins:
  - serverless-plugin-existing-s3
  - serverless-offline
  - serverless-bundle
  - serverless-pseudo-parameters

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  profile: nedian
  region: ap-south-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::we-project"

functions:
  hello:
    handler: src/handlers/index.hello
    events:
      - http:
          method: GET
          path: hello
  register:
    handler: src/handlers/index.register
    events:
      - http:
          method: POST
          path: register
  login:
    handler: src/handlers/index.login
    events:
      - http:
          method: POST
          path: login
  getUser:
    handler: src/handlers/index.getUser
    events:
      - http:
          method: GET
          path: user
  deleteUser:
    handler: src/handlers/index.deleteUser
    events:
      - http:
          method: DELETE
          path: user
  updateUser:
    handler: src/handlers/index.updateUser
    events:
      - http:
          method: PUT
          path: user
