service:
  name: we-backend

plugins:
  - serverless-plugin-existing-s3
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  profile: nedian
  region: ap-south-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::we-project"

functions:
  hello:
    handler: src/handlers/index.hello
    events:
      - http:
          method: GET
          path: hello
          cors: true
  register:
    handler: src/handlers/index.register
    events:
      - http:
          method: POST
          path: register
          cors: true
  login:
    handler: src/handlers/index.login
    events:
      - http:
          method: POST
          path: login
          cors: true
  getUser:
    handler: src/handlers/index.getUser
    events:
      - http:
          method: GET
          path: user
          cors: true
  deleteUser:
    handler: src/handlers/index.deleteUser
    events:
      - http:
          method: DELETE
          path: user
          cors: true
  updateUser:
    handler: src/handlers/index.updateUser
    events:
      - http:
          method: PUT
          path: user
          cors: true
  addQuestion:
    handler: src/handlers/index.addQuestion
    events:
      - http:
          method: POST
          path: question
          cors: true
  deleteQuestion:
    handler: src/handlers/index.deleteQuestion
    events:
      - http:
          method: DELETE
          path: question
          cors: true
  getQuestion:
    handler: src/handlers/index.getQuestion
    events:
      - http:
          method: GET
          path: question
          cors: true
